tmux new-session -d -s backup_users 'php /var/www/smsmarket/html/backend/services/users_backup.php'
tmux new-session -d -s box_data '/bin/bash /var/www/smsmarket/html/backend/services/cronstats.sh'
#tmux new-session -d -s delete '/var/www/smsmarket/html/backend/services/'
tmux new-session -d -s get_loads 'php /var/www/smsmarket/html/backend/services/get_load.php'
tmux new-session -d -s live_insert '/bin/bash /var/www/smsmarket/html/backend/services/mysql_watcher.sh'
tmux new-session -d -s refunds '/bin/bash /var/www/smsmarket/html/backend/services/refunds.sh'
tmux new-session -d -s simber_delete '/bin/bash /var/www/smsmarket/html/backend/services/featch.sh'
tmux new-session -d -s simber_sender '/bin/bash /var/www/smsmarket/html/backend/services/simberry_sender.sh'
tmux new-session -d -s users_rate '/bin/bash /var/www/smsmarket/html/backend/services/users_rate.sh'
tmux new-session -d -s waiting_list '/bin/bash /var/www/smsmarket/html/backend/services/waiting_list_redis.sh'