import mysql.connector

apiApplication = [['wp','163СOM'],
['hn','1688'],
['wj','1хbet'],
['qi','23red'],
['lh','24betting'],
['hk','4Fun'],
['ll','888casino'],
['fw','99acres'],
['ki','99app'],
['gn','A9A'],
['rh','Ace2Three'],
['ko','AdaKami'],
['bq','Adani'],
['an','Adidas'],
['sa','AGIBANK'],
['cs','AgriDevelop'],
['qu','Agroinform'],
['uk','Airbnb'],
['zl','Airtel'],
['wv','AIS'],
['jj','Aitu'],
['rf','Akudo'],
['tm','Akulaku'],
['bt','Alfa'],
['bn','Alfagift'],
['lp','Algida'],
['ab','Alibaba'],
['hx','AliExpress'],
['hw','Alipay/Alibaba'],
['yn','Allegro'],
['yo','Amasia'],
['am','Amazon'],
['ot','Any other'],
['pm','AOL'],
['ml','ApostaGanha'],
['wx','Apple'],
['gk','AptekaRU'],
['hs','Asda'],
['gr','Astropay'],
['du','AUBANK'],
['st','Auchan'],
['av','Avito'],
['ff','AVON'],
['li','Baidu'],
['hl','Band'],
['vc','Banqi'],
['cb','Bazos'],
['ck','BeReal'],
['vd','Betfair'],
['zn','Biedronka'],
['zu','BigC'],
['bl','BIGO LIVE'],
['zs','Bilibili'],
['ri','BillMill'],
['uv','BinBin'],
['ww','BIP'],
['el','Bisu'],
['qk','Bit'],
['pt','Bitaqaty'],
['lt','BitClout'],
['ht','Bitso'],
['ua','BlaBlaCar'],
['fk','BLIBLI'],
['bz','Blizzard'],
['qn','Blued'],
['tx','Bolt'],
['sy','Brahma'],
['vo','Brand20ua'],
['zt','Budweiser'],
['kh','Bukalapak'],
['mo','Bumble'],
['ip','Burger King'],
['iu','Bykea'],
['uo','CafeBazaar'],
['my','CAIXA'],
['gw','CallApp'],
['ls','Careem'],
['gj','Carousell'],
['oy','CashFly'],
['ho','Cathay'],
['pq','CDkeys'],
['ai','CELEBe'],
['td','ChaingeFinance'],
['si','Cita Previa'],
['az','CityBase'],
['yf','Citymobil'],
['hf','Cleartrip'],
['fe','CliQQ'],
['dd','CloudChat'],
['et','Clubhouse'],
['ql','CMTcuzdan'],
['oe','Codashop'],
['re','Coinbase'],
['ne','Coindcx'],
['vw','CoinField'],
['zx','CommunityGaming'],
['eg','ContactSys'],
['om','Corona'],
['yg','CourseHero'],
['wc','Craigslist'],
['ax','CrefisaMais'],
['ti','Cryptocom'],
['fr','Dana'],
['tj','DbrUA'],
['oc','DealShare'],
['zk','Deliveroo'],
['dt','Delivery Club'],
['zz','Dent'],
['xy','Depop'],
['lx','DewuPoison'],
['os','Dhani'],
['xk','DiDi'],
['zv','Digikala'],
['ds','Discord'],
['ud','Disney Hotstar'],
['dw','Divar'],
['sd','Dodopizza'],
['dz','Dominos Pizza'],
['ac','DoorDash'],
['bx','Dosi'],
['sv','Dostavista'],
['cj','Dotz'],
['ak','Douyu'],
['ve','Dream11'],
['hz','Drom'],
['we','DrugVokrug'],
['fi','Dundle'],
['le','E bike Gewinnspiel'],
['rz','EasyPay'],
['dh','EBay'],
['uf','Eneba'],
['ah','EscapeFromTarkov'],
['yj','EWallet'],
['ba','Expressmoney'],
['kr','Eyecon'],
['db','Ezbuy'],
['rm','Faberlic'],
['fb','Facebook'],
['qz','Faceit'],
['xn','Familia'],
['mr','Fastmail'],
['ug','Fiqsy'],
['cn','Fiverr'],
['xt','Flipkart'],
['iy','FoodHub'],
['nz','Foodpanda'],
['kw','Foody'],
['gu','Fora'],
['rk','Fotka'],
['kg','FreeChargeApp'],
['gq','Freelancer'],
['od','FWDMAX'],
['bk','G2G'],
['ou','Gabi'],
['xe','GalaxyChat'],
['af','GalaxyWin'],
['wn','GameArena'],
['pa','Gamekit'],
['ed','Gamer'],
['bc','GCash'],
['cg','Gemgala'],
['ul','Getir'],
['cz','Getmega'],
['gt','Gett'],
['qe','GG'],
['nn','Giftcloud'],
['nk','Gittigidiyor'],
['iz','Global24'],
['gl','GlobalTel'],
['hm','Globus'],
['aq','Glovo'],
['mq','GMNG'],
['ez','GoerliFaucet'],
['bp','GoFundMe'],
['ni','Gojek'],
['go','Google'],
['gf','GoogleVoice'],
['jg','Grab'],
['yw','Grindr'],
['ln','Grofers'],
['xs','GroupMe'],
['ik','GuruBets'],
['gh','GyFTR'],
['rp','Hamrahaval'],
['sj','HandyPick'],
['df','Happn'],
['sp','HappyFresh'],
['au','Haraj'],
['gx','Hepsiburadacom'],
['en','Hermes'],
['vx','HeyBox'],
['ss','Hezzl'],
['rt','Hily'],
['vz','Hinge'],
['ru','HOP'],
['jl','Hopi'],
['gi','Hotline'],
['kp','HQ Trivia'],
['un','Humblebundle'],
['gv','Humta'],
['pp','Huya'],
['dq','IceCasino'],
['iq','Icq'],
['cx','Icrypex'],
['pd','IFood'],
['ib','Immowelt'],
['im','Imo'],
['iv','Inboxlv'],
['tp','IndiaGold'],
['fg','IndianOil'],
['zq','IndiaPlays'],
['ju','Indomaret'],
['rl','InDriver'],
['xi','InFund'],
['hy','Ininal'],
['ig','Instagram'],
['yv','IPLwin'],
['es','IQIYI'],
['il','IQOS'],
['cf','Irancell'],
['us','IRCTC'],
['ad','Iti'],
['jc','IVI'],
['dm','Iwplay'],
['wt','IZI'],
['ea','JamesDelivery'],
['za','JDcom'],
['hr','JKF'],
['ic','JoGo'],
['xx','Joyride'],
['yx','JTExpress'],
['hi','JungleeRummy'],
['pu','Justdating'],
['zo','Kaggle'],
['kt','KakaoTalk'],
['de','Karusel'],
['jz','Kaya'],
['ol','KazanExpress'],
['bf','Keybase'],
['ra','KeyPay'],
['fz','KFC'],
['uw','Kirana'],
['kl','Kolesa.kz'],
['rv','Kotak811'],
['sq','KuCoinPlay'],
['kb','Kufarby'],
['vp','Kwai'],
['er','Kwork'],
['fh','Lalamove'],
['sb','Lamoda'],
['dl','Lazada'],
['bb','LazyPay'],
['do','Leboncoin'],
['wq','Leboncoin1'],
['rd','Lenta'],
['pz','Lidl'],
['xf','LightChat'],
['jf','Likee'],
['me','Line msg'],
['tn','LinkedIN'],
['ex','Linode'],
['eu','LiveScore'],
['di','Loanflix'],
['su','LOCO'],
['mk','LongHu'],
['rs','Lotus'],
['zi','LoveLocal'],
['dj','LUKOIL-AZS'],
['tu','Lyft'],
['gz','LYKA'],
['hq','Magicbricks'],
['mg','Magnit'],
['up','Magnolia'],
['ma','Mail.ru'],
['lb','Mailru Group'],
['fd','Mamba'],
['oh','MapleSEA'],
['bm','MarketGuru'],
['hd','MarketPapa'],
['ry','McDonalds'],
['hp','Meesho'],
['qr','MEGA'],
['lv','Megogo'],
['uy','Meliuz'],
['cq','Mercado'],
['dg','Mercari'],
['vy','Meta'],
['bv','Metro'],
['he','Mewt'],
['mc','Michat'],
['mm','Microsoft'],
['ey','Miloan'],
['op','MIRATORG'],
['bg','MIXMART'],
['gy','MIYACHAT'],
['fo','MobiKwik'],
['wk','Mobile01'],
['gm','Mocospace'],
['hc','MOMO'],
['py','Monese'],
['qo','Moneylion'],
['qg','MoneyPay'],
['qt','MoneyСontrol'],
['ji','Monobank'],
['bu','MonobankIndia'],
['ce','Mosru'],
['xq','MPL'],
['lw','MrGreen'],
['ej','MrQ'],
['da','MTS CashBack'],
['ha','My11Circle'],
['ur','MyDailyCash'],
['qa','MyFishka'],
['ae','MyGLO'],
['fy','Mylove'],
['mu','MyMusicTaste'],
['nl','Myntra'],
['jm','Mzadqatar'],
['je','Nanovest'],
['nv','Naver'],
['sw','NCsoft'],
['nf','Netflix'],
['ef','Nextdoor'],
['px','Nifty'],
['ew','Nike'],
['kz','NimoTV'],
['dv','NoBroker'],
['tf','Noon'],
['pg','NRJ Music Awards'],
['zy','Nttgame'],
['zm','OfferUp'],
['uz','OffGamers'],
['ok','Ok.ru'],
['vm','OkCupid'],
['og','Okko'],
['lr','Okta'],
['ly','Olacabs'],
['sn','OLX'],
['aj','OneAset'],
['ue','Onet'],
['ob','Onlinerby'],
['zf','OnTaxi'],
['dr','OpenAI'],
['qh','Oriflame'],
['xh','OVO'],
['sg','OZON'],
['cw','PaddyPower'],
['gg','PagSmile'],
['dk','Pairs'],
['zr','Papara'],
['wo','Parkplus'],
['dn','Paxful'],
['qb','Payberry'],
['xz','Paycell'],
['ts','PayPal'],
['jq','Paysafecard'],
['tr','Paysend'],
['ge','Paytm'],
['yp','Payzapp'],
['pl','Perekrestok'],
['at','Perfluence'],
['fx','PGbonus'],
['fc','PharmEasy'],
['fp','Phound'],
['ev','Picpay'],
['jh','PingPong'],
['sz','Pivko24'],
['ch','Pocket52'],
['pf','Pof.com'],
['rg','Porbet'],
['oz','Poshmark'],
['lq','Potato'],
['fj','Potato Chat'],
['dx','Powerkredite'],
['po','Premium.one'],
['aa','Probo'],
['cm','Prom'],
['dp','ProtonMail'],
['lk','PurePlatfrom'],
['ny','Pyro Music'],
['vf','Q12 Trivia'],
['qw','Qiwi'],
['eq','Qoo10'],
['zw','Quack'],
['cc','Quipp'],
['tc','Rambler'],
['xu','RecargaPay'],
['qf','RedBook'],
['ci','RedBus'],
['co','Rediffmail'],
['ij','Revolut'],
['zj','ROBINHOOD'],
['ga','Roposo'],
['qm','RosaKhutor'],
['ku','RoyalWin'],
['km','Rozetka'],
['mn','RRSA'],
['ec','RummyCulture'],
['fl','RummyLoot'],
['xb','RummyOla'],
['so','RummyWealth'],
['ay','Ruten'],
['ui','RuTube'],
['gs','SamsungShop'],
['lj','Santander'],
['pw','SellMonitor'],
['vv','Seosprint'],
['zg','Setel'],
['rx','Sheerid'],
['vg','ShellBox'],
['ka','Shopee'],
['bw','Signal'],
['fs','Şikayet var'],
['np','Siply'],
['eo','Sizeer'],
['wg','Skout'],
['sk','Skroutz'],
['rc','Skype'],
['fu','Snapchat'],
['ph','SnappFood'],
['sf','SneakersnStuff'],
['ia','Socios'],
['mx','SoulApp'],
['ky','SpatenOktoberfest'],
['va','SportGully'],
['cd','SpotHit'],
['la','Ssoidnet'],
['sr','Starbucks'],
['mt','Steam'],
['hj','Stoloto'],
['vj','Stormgain'],
['nu','Stripe'],
['lc','Subito'],
['ca','SuperS'],
['gd','Surveytime'],
['jx','Swiggy'],
['hg','Switips'],
['tq','Swvl'],
['aw','Taikang'],
['xw','Taki'],
['ei','Taksheel'],
['xr','Tango'],
['wh','TanTan'],
['qd','Taobao'],
['uc','Tatneft'],
['ih','TeenPattiStarpro'],
['tg','Telegram'],
['eh','Telegram 2.0'],
['ep','Temu'],
['qq','Tencent QQ'],
['cr','TenChat'],
['nm','Thisshop'],
['rb','Tick'],
['gp','Ticketmaster'],
['lf','TikTok/Douyin'],
['oi','Tinder'],
['xd','Tokopedia'],
['nr','Tosla'],
['fm','Touchance'],
['bs','TradeUP'],
['gc','TradingView'],
['pr','Trendyol'],
['nq','Trip'],
['tl','Truecaller'],
['jt','TurkiyePetrolleri'],
['ee','Twilio'],
['hb','Twitch'],
['tw','Twitter'],
['ub','Uber'],
['cp','Uklon'],
['hu','Ukrnet'],
['hh','Uplay'],
['of','Urent'],
['bh','Uteka'],
['ao','UU163'],
['cl','UWIN'],
['yy','Venmo'],
['kn','Verse'],
['vi','Viber'],
['fv','Vidio'],
['kc','Vinted'],
['no','Virgo'],
['kx','Vivo'],
['vk','Vk.com'],
['sh','Vkusvill'],
['oq','Vlife'],
['eb','Voltz'],
['cv','WashXpress'],
['wb','WeChat'],
['kf','Weibo'],
['mf','Weidian'],
['th','WestStein'],
['ja','Weverse'],
['wa','Whatsapp'],
['qj','Whoosh'],
['uu','Wildberries'],
['jb','Wing Money'],
['ta','Wink'],
['vs','WinzoGame'],
['bo','Wise'],
['xv','Wish'],
['xl','Wmaraci'],
['rr','Wolt'],
['ar','Wondermart'],
['bd','X5ID'],
['fa','XadrezFeliz'],
['yu','Xiaomi'],
['nw','Ximalaya'],
['vn','Yaay'],
['mb','Yahoo'],
['yl','Yalla'],
['ya','Yandex'],
['wf','YandexGo'],
['kj','YAPPY'],
['yi','Yemeksepeti'],
['dc','YikYak'],
['wl','YouGotaGift'],
['ym','Youla.ru'],
['gb','YouStar'],
['sm','YoWin'],
['uh','Yubo'],
['mj','Zalo'],
['ys','ZCity'],
['em','ZéDelivery'],
['qy','Zhihu'],
['tt','Ziglu'],
['zd','Zilch'],
['zh','Zoho'],
['dy','Zomato'],
['mi','Zupee'],
['mh','Ашан'],
['md','Банки'],
['ft','Букмекерские'],
['nb','Верный'],
['bj','Вита экспресс'],
['br','Вкусно и Точка'],
['rj','Детский мир'],
['io','ЗдравСити'],
['fq','Контур'],
['ct','КухняНаРайоне'],
['xm','Лэтуаль'],
['tk','МВидео'],
['yz','Около'],
['qc','Праймериз 2020'],
['cy','РСА'],
['uj','СhampionСasino'],
['jr','Самокат'],
['sl','СберАптека'],
['xj','СберМаркет'],
['be','СберМегаМаркет'],
['yb','Система Город'],
['yk','СпортМастер'],
['yq','Фокстрот'],
['ke','Эльдорадо'],
['bi','勇仕网络Ys4fun'],
['cu','炙热星河'],
['yd','米画师Mihuashi']
]

country_list = [['Afghanistan','AF'],
['Albania','AL'],
['Algeria','DZ'],
['American Samoa','AS'],
['Andorra','AD'],
['Angola','AO'],
['Anguilla','AI'],
['Antarctica','AQ'],
['Antigua and Barbuda','AG'],
['Argentina','AR'],
['Armenia','AM'],
['Aruba','AW'],
['Australia','AU'],
['Austria','AT'],
['Azerbaijan','AZ'],
['Bahamas','BS'],
['Bahrain','BH'],
['Bangladesh','BD'],
['Barbados','BB'],
['Belarus','BY'],
['Belgium','BE'],
['Belize','BZ'],
['Benin','BJ'],
['Bermuda','BM'],
['Bhutan','BT'],
['Bolivia','BO'],
['Bosnia and Herzegovina','BA'],
['Botswana','BW'],
['Brazil','BR'],
['British Indian Ocean Territory','IO'],
['British Virgin Islands','VG'],
['Brunei','BN'],
['Bulgaria','BG'],
['Burkina Faso','BF'],
['Burundi','BI'],
['Cambodia','KH'],
['Cameroon','CM'],
['Canada','CA'],
['Cape Verde','CV'],
['Cayman Islands','KY'],
['Central African Republic','CF'],
['Chad','TD'],
['Chile','CL'],
['China','CN'],
['Christmas Island','CX'],
['Cocos Islands','CC'],
['Colombia','CO'],
['Comoros','KM'],
['Cook Islands','CK'],
['Costa Rica','CR'],
['Croatia','HR'],
['Cuba','CU'],
['Curacao','CW'],
['Cyprus','CY'],
['Czech Republic','CZ'],
['Democratic Republic of the Congo','CD'],
['Denmark','DK'],
['Djibouti','DJ'],
['Dominica','DM'],
['Dominican Republic','DO'],
['East Timor','TL'],
['Ecuador','EC'],
['Egypt','EG'],
['El Salvador','SV'],
['Equatorial Guinea','GQ'],
['Eritrea','ER'],
['Estonia','EE'],
['Ethiopia','ET'],
['Falkland Islands','FK'],
['Faroe Islands','FO'],
['Fiji','FJ'],
['Finland','FI'],
['France','FR'],
['French Polynesia','PF'],
['Gabon','GA'],
['Gambia','GM'],
['Georgia','GE'],
['Germany','DE'],
['Ghana','GH'],
['Gibraltar','GI'],
['Greece','GR'],
['Greenland','GL'],
['Grenada','GD'],
['Guam','GU'],
['Guatemala','GT'],
['Guernsey','GG'],
['Guinea','GN'],
['Guineasau','GW'],
['Guyana','GY'],
['Haiti','HT'],
['Honduras','HN'],
['Hong Kong','HK'],
['Hungary','HU'],
['Iceland','IS'],
['India','IN'],
['Indonesia','ID'],
['Iran','IR'],
['Iraq','IQ'],
['Ireland','IE'],
['Isle of Man','IM'],
['Italy','IT'],
['Ivory Coast','CI'],
['Jamaica','JM'],
['Japan','JP'],
['Jersey','JE'],
['Jordan','JO'],
['Kazakhstan','KZ'],
['Kenya','KE'],
['Kiribati','KI'],
['Kosovo','XK'],
['Kuwait','KW'],
['Kyrgyzstan','KG'],
['Laos','LA'],
['Latvia','LV'],
['Lebanon','LB'],
['Lesotho','LS'],
['Liberia','LR'],
['Libya','LY'],
['Liechtenstein','LI'],
['Lithuania','LT'],
['Luxembourg','LU'],
['Macau','MO'],
['Macedonia','MK'],
['Madagascar','MG'],
['Malawi','MW'],
['Malaysia','MY'],
['Maldives','MV'],
['Mali','ML'],
['Malta','MT'],
['Marshall Islands','MH'],
['Mauritania','MR'],
['Mauritius','MU'],
['Mayotte','YT'],
['Mexico','MX'],
['Micronesia','FM'],
['Moldova','MD'],
['Monaco','MC'],
['Mongolia','MN'],
['Montenegro','ME'],
['Montserrat','MS'],
['Morocco','MA'],
['Mozambique','MZ'],
['Myanmar','MM'],
['Namibia','NA'],
['Nauru','NR'],
['Nepal','NP'],
['Netherlands','NL'],
['Netherlands Antilles','AN'],
['New Caledonia','NC'],
['New Zealand','NZ'],
['Nicaragua','NI'],
['Niger','NE'],
['Nigeria','NG'],
['Niue','NU'],
['North Korea','KP'],
['Northern Mariana Islands','MP'],
['Norway','NO'],
['null','0'],
['Oman','OM'],
['Pakistan','PK'],
['Palau','PW'],
['Palestine','PS'],
['palestine','PS'],
['Panama','PA'],
['Papua New Guinea','PG'],
['Paraguay','PY'],
['Peru','PE'],
['Philippines','PH'],
['Pitcairn','PN'],
['Poland','PL'],
['Portugal','PT'],
['Puerto Rico','PR'],
['Qatar','QA'],
['Republic of the Congo','CG'],
['Reunion','RE'],
['Romania','RO'],
['Russia','RU'],
['Rwanda','RW'],
['Saint Barthelemy','BL'],
['Saint Helena','SH'],
['Saint Kitts and Nevis','KN'],
['Saint Lucia','LC'],
['Saint Martin','MF'],
['Saint Pierre and Miquelon','PM'],
['Saint Vincent and the Grenadines','VC'],
['Samoa','WS'],
['San Marino','SM'],
['Sao Tome and Principe','ST'],
['Saudi Arabia','SA'],
['Senegal','SN'],
['Serbia','RS'],
['Seychelles','SC'],
['Sierra Leone','SL'],
['Singapore','SG'],
['Sint Maarten','SX'],
['Slovakia','SK'],
['Slovenia','SI'],
['Solomon Islands','SB'],
['Somalia','SO'],
['South Africa','ZA'],
['South Korea','KR'],
['South Sudan','SS'],
['Spain','ES'],
['Sri Lanka','LK'],
['Sudan','SD'],
['Suriname','SR'],
['Svalbard and Jan Mayen','SJ'],
['Swaziland','SZ'],
['Sweden','SE'],
['Switzerland','CH'],
['Syria','SY'],
['Taiwan','TW'],
['Tajikistan','TJ'],
['Tanzania','TZ'],
['Thailand','TH'],
['Togo','TG'],
['Tokelau','TK'],
['Tonga','TO'],
['Trinidad and Tobago','TT'],
['Tunisia','TN'],
['Turkey','TR'],
['Turkmenistan','TM'],
['Turks and Caicos Islands','TC'],
['Tuvalu','TV'],
['U.S. Virgin Islands','VI'],
['Uganda','UG'],
['Ukraine','UA'],
['United Arab Emirates','AE'],
['United Kingdom','GB'],
['United States','US'],
['Uruguay','UY'],
['Uzbekistan','UZ'],
['Vanuatu','VU'],
['Vatican','VA'],
['Venezuela','VE'],
['Vietnam','VN'],
['Wallis and Futuna','WF'],
['Western Sahara','EH'],
['Yemen','YE'],
['Zambia','ZM'],
['Zimbabwe','ZW']
]

mineapplication = dict()
mineapplication['Instagram']='in'
mineapplication['Telegram']='te'
mineapplication['Google']='go'
mineapplication['Accuindex']='ac'
mineapplication['TikTok']='ti'
mineapplication['Apple']='ap'
mineapplication['Imo']='im'
mineapplication['WhatsApp']='wa'
mineapplication['Facebook']='fa'

cnx = mysql.connector.connect(
    host='localhost',
    user='mixsimverify',
    password='SMS@mixsimverify.com',
    database='smsdb'
)
cursor = cnx.cursor()
main_string = ''
valuestring = ''
count = 0
comma=''

for apiapp in apiApplication:
    print(apiapp[0])
    continue
    apiappcode = apiapp[0]
    apiappname = apiapp[1]
    myappcode = ''
    myappname = apiappname
    if apiappname in mineapplication.keys():
        myappcode = mineapplication[apiappname]
    else:
        myappcode = apiappcode

    for country in country_list:
        count+=1
        country_name = country[0]
        country_code = country[1]

        main_query = "INSERT INTO `foreignapiservice` ( `Name`, `code`, `price_in`, `price_out`, `acc_price_out`, `max_numbers`, `availability`, `Id_Foreign_Api`, `description`, `country`, `country_name`, `service_of_api`, `country_of_api`, `is_deleted`,`carrier`) VALUES (%s, %s, 0.1, 1, 0.2, 999, 9999, 23, 'jkatel-partner', %s, %s, %s,%s,0,' ')"
        #print(main_query)
        cursor.execute(main_query, (myappname,myappcode,country_code,country_name,apiappcode,country_name))
        cnx.commit() 
cursor.close()
cnx.close()
print("Finish")





